### ISSUE TITLE
Cannot update or edit existing time entries on Fedora 28 xfce

### ISSUE THREAD

**Issue by geetotes** [projecthamster/xfce4-hamster-plugin#33]
I cannot update or edit existing time entries on Fedora 28 with xfce. When I click the edit icon, I expect my time entry to re-appear in the text field below "What goes on?", but nothing happens. When I got into "show overview" and try to edit entries from there, nothing happens either.

This it the traceback I found in `/var/log/messages`:
```
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]: Traceback (most recent call last):
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:  File "/usr/lib/python2.7/site-packages/hamster/overview.py", line 481, in on_row_activated
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:    dialogs.edit.show(self, fact_date=fact.date, fact_id=fact.id)
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:  File "/usr/lib/python2.7/site-packages/hamster/lib/configuration.py", line 153, in show
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:    dialog = self.get_dialog_class()(parent, **kwargs)
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:  File "/usr/lib/python2.7/site-packages/hamster/edit_activity.py", line 47, in __init__
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:    self.activity = widgets.ActivityEntry()
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:  File "/usr/lib/python2.7/site-packages/hamster/widgets/activityentry.py", line 211, in __init__
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:    self.load_suggestions()
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:  File "/usr/lib/python2.7/site-packages/hamster/widgets/activityentry.py", line 288, in load_suggestions
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]:    label += "@%s" % fact.category
Nov  8 13:40:16 cuttlefish org.gnome.Hamster.WindowServer[1322]: TypeError: unsupported operand type(s) for +=: 'NoneType' and 'unicode'
```

Maybe Fedora28 runs some type of unicode for text encoding that is not recongized during the edit operation? This plugin has worked perfectly on older versions of Fedora, and I thank you very much for your hard work making it.

**Comment by aquaherd** [comment]
Sorry for the late response, I will look into it however I'll need to set up a Fedora 28 vm first.

**Comment by aquaherd** [comment]
Strange. This absolutely works in F29.
